name: Test coverage

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      #       checkout
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install dependencies
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -DJDBC_DATABASE_URL=${{secrets.JDBC_DATABASE_URL}} -B -V
      - name: Run tests and collect coverage
        run: mvn -B test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3


