name: Test coverage

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      #       checkout
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      #       build project and run all tests & checks
      - name: Maven Verify
        run: mvn -B clean verify -DJDBC_DATABASE_URL=${{secrets.JDBC_DATABASE_URL}}

      #       Upload code coverage report to Codecov
      - name: Test Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./site
          files: ./jacoco.xml